
# Block design: XDMA + HBM + CVA6 + bootrom + 16550 UART + finisher + ctrl + I2C
#
# Forest Kitten 33 (xcvu33p) variant of the cva6_xdma design.
# Modeled on SQRL_FK33/projects/fk33_example.tcl for HBM/clocking/PCIe topology.
# Guest-visible peripherals mirror the QEMU `virt` machine (UART0 @ 0x10000000,
# VIRT_TEST finisher @ 0x100000, DRAM @ 0x80000000) so the same baremetal RV64
# binary runs on QEMU and the card. ctrl_regs is host-only (CVA6 reset).
#
# Fabric clock: 250 MHz (xdma_0/axi_aclk). At Gen3 x4 the XDMA's axi-stream
# clock is fixed at 250 MHz. The SmartConnect, HBM AXI, and all peripherals
# run at 250 MHz. HBM ref clocks are 200 MHz and the HBM controller APB runs
# at 100 MHz — both generated by clk_wiz_0.
#
# Address map (unified — both XDMA host master and CVA6 see the same map):
#   0x0001_0000 .. 0x0001_0FFF   bootrom        (4 KB BRAM, CVA6 reset vector)
#   0x0010_0000 .. 0x0010_0FFF   sifive_test    (finisher / exit; QEMU VIRT_TEST)
#   0x1000_0000 .. 0x1001_FFFF   uart16550      (guest regs @ +0; TX-drain @ +0x10000)
#   0x6000_0000 .. 0x6000_000F   ctrl regs      (host-only: CVA6 reset / doorbell)
#   0x6001_0000 .. 0x6001_0FFF   axi_iic        (PMIC / on-board LEDs)
#   0x8000_0000 .. 0xBFFF_FFFF   HBM            (first 1 GiB of stack 0)
#
# HBM SAXI_00 native MEM00..MEM03 (each 256 MB) are remapped to 0x80000000..
# 0xBFFFFFFF on the master side via the SmartConnect. The remaining 28 HBM
# segments stay unmapped (and inaccessible) for this 1 GiB window.

##############
# PCIe / XDMA  — Gen3 x4 on PCIE4C_X1Y0
##############

create_bd_cell -type ip -vlnv xilinx.com:ip:xdma:4.1 xdma_0
# Stage 1: lock down PCIe block + link width/speed. axisten_freq's valid set
# depends on these — at Gen3 x4 the AXI-stream clock must be 250 MHz.
set_property -dict [list \
    CONFIG.pcie_blk_locn                {PCIE4C_X1Y0} \
    CONFIG.pl_link_cap_max_link_width   {X4} \
    CONFIG.pl_link_cap_max_link_speed   {8.0_GT/s} \
    CONFIG.ref_clk_freq                 {100_MHz} \
] [get_bd_cells xdma_0]
# Stage 2: fabric clock + interface mode.
set_property -dict [list \
    CONFIG.axisten_freq                 {250} \
    CONFIG.xdma_axi_intf_mm             {AXI_Memory_Mapped} \
    CONFIG.xdma_pcie_64bit_en           {true} \
] [get_bd_cells xdma_0]
# Stage 3: PCIe class code. The IP default for PF0 is 0x070001 ("serial
# controller, 16550"), which makes the kernel's built-in 8250/serial driver
# claim the endpoint at boot before the Xilinx xdma driver loads -> no
# /dev/xdma0_* nodes. Present it as a Memory controller (0x058000) instead so
# only the xdma driver binds it. (Mirrors this IP's own PF2 defaults.)
set_property -dict [list \
    CONFIG.pf0_base_class_menu          {Memory_controller} \
    CONFIG.pf0_class_code_base          {05} \
    CONFIG.pf0_sub_class_interface_menu {Other_memory_controller} \
    CONFIG.pf0_class_code_sub           {80} \
    CONFIG.pf0_class_code_interface     {00} \
] [get_bd_cells xdma_0]

# PCIe MGT lanes (top-level interface named "pcie")
make_bd_intf_pins_external [get_bd_intf_pins xdma_0/pcie_mgt]
set_property name pcie [get_bd_intf_ports pcie_mgt_0]

# PCIe 100 MHz refclk (diff pair via util_ds_buf in IBUFDSGTE mode)
create_bd_cell -type ip -vlnv xilinx.com:ip:util_ds_buf:2.2 util_ds_buf_pcie
set_property CONFIG.C_BUF_TYPE {IBUFDSGTE} [get_bd_cells util_ds_buf_pcie]
make_bd_intf_pins_external [get_bd_intf_pins util_ds_buf_pcie/CLK_IN_D]
set_property name pcie_refclk [get_bd_intf_ports CLK_IN_D_0]
connect_bd_net [get_bd_pins util_ds_buf_pcie/IBUF_DS_ODIV2] [get_bd_pins xdma_0/sys_clk]
connect_bd_net [get_bd_pins util_ds_buf_pcie/IBUF_OUT]      [get_bd_pins xdma_0/sys_clk_gt]

# PERST_N from the slot
make_bd_pins_external [get_bd_pins xdma_0/sys_rst_n]
set_property CONFIG.POLARITY ACTIVE_LOW [get_bd_ports sys_rst_n_0]
set_property name pcie_perstn [get_bd_ports sys_rst_n_0]

# CLKREQ# — tied constant high (some slots require it driven)
create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant:1.1 clkreq_const
set_property CONFIG.CONST_VAL {1} [get_bd_cells clkreq_const]
make_bd_pins_external [get_bd_pins clkreq_const/dout]
set_property name pcie_clkreq [get_bd_ports dout_0]

##############
# HBM (8 GiB total, global switch on — SAXI_00 reaches all channels)
##############

create_bd_cell -type ip -vlnv xilinx.com:ip:hbm:1.0 hbm_0
set_property -dict [list \
    CONFIG.USER_HBM_DENSITY              {8GB} \
    CONFIG.USER_HBM_STACK                {2} \
    CONFIG.USER_MEMORY_DISPLAY           {8192} \
    CONFIG.USER_HBM_REF_CLK_0            {200} \
    CONFIG.USER_HBM_REF_CLK_1            {200} \
    CONFIG.USER_AXI_INPUT_CLK_FREQ       {250} \
    CONFIG.USER_AXI_INPUT_CLK1_FREQ      {250} \
    CONFIG.USER_APB_EN                   {false} \
    CONFIG.USER_CLK_SEL_LIST0            {AXI_00_ACLK} \
    CONFIG.USER_CLK_SEL_LIST1            {AXI_16_ACLK} \
] [get_bd_cells hbm_0]

# Disable all SAXI ports except SAXI_00 (only master we use; global switch
# lets SAXI_00 reach all 32 channels across both stacks).
foreach i {01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31} {
    set_property CONFIG.USER_SAXI_$i {false} [get_bd_cells hbm_0]
}

##############
# Clock generation
#   sysclk_200 = 200 MHz free-running board oscillator (FK33 SYSCLK0_200,
#                Si5335A). It drives the HBM reference clocks directly and the
#                MMCM input. The old topology fed the MMCM from xdma/axi_aclk
#                (a PCIe GT clock-modifying-block output) and the HBM ref from
#                an MMCM output (clk_out2), which produced the TIMING-3/4/27
#                clock-redefinition critical warnings. The board file marks this
#                oscillator preferred_ip=hbm — it is the intended HBM ref clock.
#   clk_in1  = 200 MHz from sysclk_200
#   clk_out1 = 100 MHz APB clock for HBM controller APB
#   clk_out2 = cpu_freq_mhz CVA6 clock
#   (HBM_REF_CLK_0/1 now come straight from sysclk_200, not the MMCM.)
##############

# Differential input buffer for the 200 MHz oscillator (pins set in the XDC).
create_bd_cell -type ip -vlnv xilinx.com:ip:util_ds_buf:2.2 sysclk_buf
set_property CONFIG.C_BUF_TYPE {IBUFDS} [get_bd_cells sysclk_buf]
make_bd_intf_pins_external [get_bd_intf_pins sysclk_buf/CLK_IN_D]
set_property name sysclk_200 [get_bd_intf_ports CLK_IN_D_0]
# Declare the oscillator as 200 MHz so the frequency propagates through the
# IBUFDS to clk_wiz_0/clk_in1 (otherwise it defaults to 100 MHz and mismatches).
set_property CONFIG.FREQ_HZ 200000000 [get_bd_intf_ports sysclk_200]

create_bd_cell -type ip -vlnv xilinx.com:ip:clk_wiz:6.0 clk_wiz_0
set_property -dict [list \
    CONFIG.PRIM_SOURCE                  {Global_buffer} \
    CONFIG.PRIM_IN_FREQ                 {200.000} \
    CONFIG.RESET_TYPE                   {ACTIVE_LOW} \
    CONFIG.RESET_PORT                   {resetn} \
    CONFIG.USE_LOCKED                   {true} \
    CONFIG.CLKOUT1_USED                 {true} \
    CONFIG.CLKOUT1_REQUESTED_OUT_FREQ   {100.000} \
    CONFIG.CLKOUT2_USED                 {true} \
    CONFIG.CLKOUT2_REQUESTED_OUT_FREQ   $cpu_freq_mhz \
] [get_bd_cells clk_wiz_0]
connect_bd_net [get_bd_pins sysclk_buf/IBUF_OUT] [get_bd_pins clk_wiz_0/clk_in1]
connect_bd_net [get_bd_pins xdma_0/axi_aresetn]  [get_bd_pins clk_wiz_0/resetn]

# Reset for HBM domain (100 MHz APB clock)
create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 hbm_reset
connect_bd_net [get_bd_pins clk_wiz_0/clk_out1]  [get_bd_pins hbm_reset/slowest_sync_clk]
connect_bd_net [get_bd_pins clk_wiz_0/locked]    [get_bd_pins hbm_reset/dcm_locked]
connect_bd_net [get_bd_pins xdma_0/axi_aresetn]  [get_bd_pins hbm_reset/ext_reset_in]

# HBM clock/reset wiring
connect_bd_net [get_bd_pins sysclk_buf/IBUF_OUT]     [get_bd_pins hbm_0/HBM_REF_CLK_0]
connect_bd_net [get_bd_pins sysclk_buf/IBUF_OUT]     [get_bd_pins hbm_0/HBM_REF_CLK_1]
connect_bd_net [get_bd_pins clk_wiz_0/clk_out1]      [get_bd_pins hbm_0/APB_0_PCLK]
connect_bd_net [get_bd_pins clk_wiz_0/clk_out1]      [get_bd_pins hbm_0/APB_1_PCLK]
connect_bd_net [get_bd_pins hbm_reset/peripheral_aresetn] [get_bd_pins hbm_0/APB_0_PRESET_N]
connect_bd_net [get_bd_pins hbm_reset/peripheral_aresetn] [get_bd_pins hbm_0/APB_1_PRESET_N]
connect_bd_net [get_bd_pins xdma_0/axi_aclk]         [get_bd_pins hbm_0/AXI_00_ACLK]
connect_bd_net [get_bd_pins xdma_0/axi_aresetn]      [get_bd_pins hbm_0/AXI_00_ARESET_N]

##############
# CPU clock domain reset
##############

create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 cpu_rstgen
connect_bd_net [get_bd_pins clk_wiz_0/clk_out2]  [get_bd_pins cpu_rstgen/slowest_sync_clk]
connect_bd_net [get_bd_pins clk_wiz_0/locked]    [get_bd_pins cpu_rstgen/dcm_locked]
connect_bd_net [get_bd_pins xdma_0/axi_aresetn]  [get_bd_pins cpu_rstgen/ext_reset_in]

##############
# CVA6 wrapper
##############

create_bd_cell -type module -reference cva6_acorn_wrapper cva6_0
connect_bd_net [get_bd_pins clk_wiz_0/clk_out2] [get_bd_pins cva6_0/clk]

# CVA6 master → axi_aclk SmartConnect
create_bd_cell -type ip -vlnv xilinx.com:ip:axi_clock_converter:2.1 cva6_axi_cc
connect_bd_intf_net [get_bd_intf_pins cva6_0/m_axi] [get_bd_intf_pins cva6_axi_cc/S_AXI]
connect_bd_net [get_bd_pins clk_wiz_0/clk_out2]            [get_bd_pins cva6_axi_cc/s_axi_aclk]
connect_bd_net [get_bd_pins cpu_rstgen/peripheral_aresetn] [get_bd_pins cva6_axi_cc/s_axi_aresetn]
connect_bd_net [get_bd_pins xdma_0/axi_aclk]               [get_bd_pins cva6_axi_cc/m_axi_aclk]
connect_bd_net [get_bd_pins xdma_0/axi_aresetn]            [get_bd_pins cva6_axi_cc/m_axi_aresetn]

##############
# AXI SmartConnect — 2 masters (XDMA, CVA6), 6 slaves
#   M00: HBM SAXI_00
#   M01: bootrom
#   M02: uart16550   (guest 16550 regs + host TX-drain window)
#   M03: ctrl_regs   (host-only: CVA6 reset / doorbell)
#   M04: axi_iic     (PMIC + LEDs)
#   M05: sifive_test (finisher / exit)
##############

create_bd_cell -type ip -vlnv xilinx.com:ip:smartconnect:1.0 axi_smc
set_property -dict [list \
    CONFIG.NUM_SI {2} \
    CONFIG.NUM_MI {6} \
    CONFIG.NUM_CLKS {1} \
] [get_bd_cells axi_smc]
connect_bd_net [get_bd_pins xdma_0/axi_aclk]    [get_bd_pins axi_smc/aclk]
connect_bd_net [get_bd_pins xdma_0/axi_aresetn] [get_bd_pins axi_smc/aresetn]

connect_bd_intf_net [get_bd_intf_pins xdma_0/M_AXI]      [get_bd_intf_pins axi_smc/S00_AXI]
connect_bd_intf_net [get_bd_intf_pins cva6_axi_cc/M_AXI] [get_bd_intf_pins axi_smc/S01_AXI]
connect_bd_intf_net [get_bd_intf_pins axi_smc/M00_AXI]   [get_bd_intf_pins hbm_0/SAXI_00]

##############
# Bootrom (4 KB at 0x10000)
##############

create_bd_cell -type module -reference axi_bram_init bootrom_0
set_property -dict [list \
    CONFIG.MEM_INIT_FILE {bootrom.memh} \
    CONFIG.DEPTH_WORDS   {1024} \
] [get_bd_cells bootrom_0]
connect_bd_net [get_bd_pins xdma_0/axi_aclk]    [get_bd_pins bootrom_0/axi_clk]
connect_bd_net [get_bd_pins xdma_0/axi_aresetn] [get_bd_pins bootrom_0/axi_resetn]
connect_bd_intf_net [get_bd_intf_pins axi_smc/M01_AXI] [get_bd_intf_pins bootrom_0/s_axi]

##############
# UART 16550 (128 KB window at 0x10000000)
#   0x10000000..0x1000_0007  guest 16550 register map (QEMU virt UART0)
#   0x10010000               host TX-drain: tx_len (offset 0), payload (>=8)
##############

create_bd_cell -type module -reference axi_uart16550 uart_0
connect_bd_net [get_bd_pins xdma_0/axi_aclk]    [get_bd_pins uart_0/axi_clk]
connect_bd_net [get_bd_pins xdma_0/axi_aresetn] [get_bd_pins uart_0/axi_resetn]
connect_bd_intf_net [get_bd_intf_pins axi_smc/M02_AXI] [get_bd_intf_pins uart_0/s_axi]

##############
# Control registers (16 B at 0x60000000)
##############

create_bd_cell -type module -reference axi_ctrl_regs ctrl_0
connect_bd_net [get_bd_pins xdma_0/axi_aclk]    [get_bd_pins ctrl_0/axi_clk]
connect_bd_net [get_bd_pins xdma_0/axi_aresetn] [get_bd_pins ctrl_0/axi_resetn]
connect_bd_intf_net [get_bd_intf_pins axi_smc/M03_AXI] [get_bd_intf_pins ctrl_0/s_axi]

# CVA6 reset: feed the host-controlled reset (ctrl_regs/cva6_rst_n, launched in
# the ui_clk/axi domain) through cpu_rstgen's aux_reset_in so proc_sys_reset
# synchronises its release to cpu_clk. This replaces the old combinational AND,
# which crossed ui_clk->cpu_clk (related clocks via the MMCM) unsynchronised and
# produced a ~23k-fanout reset with negative hold slack. aux_reset_in is
# active-low by default, matching cva6_rst_n.
connect_bd_net [get_bd_pins ctrl_0/cva6_rst_n]             [get_bd_pins cpu_rstgen/aux_reset_in]
connect_bd_net [get_bd_pins cpu_rstgen/peripheral_aresetn] [get_bd_pins cva6_0/rst_n]

# Host→CVA6 IRQ (PLIC src 1). CVA6→host IRQ (XDMA usr_irq) is now driven by the
# sifive_test finisher (guest writes 0x5555/0x3333 -> usr_irq). ctrl_0's
# host_irq_out is left unconnected (vestigial until removed).
connect_bd_net [get_bd_pins ctrl_0/host_irq]     [get_bd_pins cva6_0/host_irq]

##############
# AXI I2C (PMIC + 7 LEDs)
##############

create_bd_cell -type ip -vlnv xilinx.com:ip:axi_iic:2.1 axi_iic_0
set_property -dict [list \
    CONFIG.C_GPO_WIDTH    {7} \
    CONFIG.C_DEFAULT_VALUE {0x40} \
] [get_bd_cells axi_iic_0]
connect_bd_net [get_bd_pins xdma_0/axi_aclk]    [get_bd_pins axi_iic_0/s_axi_aclk]
connect_bd_net [get_bd_pins xdma_0/axi_aresetn] [get_bd_pins axi_iic_0/s_axi_aresetn]
connect_bd_intf_net [get_bd_intf_pins axi_smc/M04_AXI] [get_bd_intf_pins axi_iic_0/S_AXI]
make_bd_intf_pins_external [get_bd_intf_pins axi_iic_0/IIC]
set_property name iic [get_bd_intf_ports IIC_0]

# LEDs: GPO inverted (LEDs are active-low on FK33)
create_bd_cell -type ip -vlnv xilinx.com:ip:util_vector_logic:2.0 led_inv
set_property -dict [list CONFIG.C_OPERATION {not} CONFIG.C_SIZE {7}] [get_bd_cells led_inv]
connect_bd_net [get_bd_pins axi_iic_0/gpo] [get_bd_pins led_inv/Op1]
make_bd_pins_external [get_bd_pins led_inv/Res]
set_property name led [get_bd_ports Res_0]

##############
# SiFive test finisher (4 KB at 0x100000) — QEMU virt VIRT_TEST.
# Guest writes 0x5555 (pass) / 0x3333 (fail) here to exit; that raises the
# XDMA usr_irq so the host wakes, then reads back the latched result.
##############

create_bd_cell -type module -reference axi_sifive_test finisher_0
connect_bd_net [get_bd_pins xdma_0/axi_aclk]    [get_bd_pins finisher_0/axi_clk]
connect_bd_net [get_bd_pins xdma_0/axi_aresetn] [get_bd_pins finisher_0/axi_resetn]
connect_bd_intf_net [get_bd_intf_pins axi_smc/M05_AXI] [get_bd_intf_pins finisher_0/s_axi]
connect_bd_net [get_bd_pins finisher_0/test_irq] [get_bd_pins xdma_0/usr_irq_req]

##############
# Address map — both XDMA and CVA6 see the unified map.
# HBM SAXI_00/HBM_MEM00..03 are placed at 0x80000000 (1 GiB window).
##############

set masters {/xdma_0/M_AXI /cva6_0/m_axi}

foreach master $masters {
    set tag [expr {$master eq "/xdma_0/M_AXI" ? "xdma" : "cva6"}]
    create_bd_addr_seg -range 4K   -offset 0x00010000 \
        [get_bd_addr_spaces $master] \
        [get_bd_addr_segs {/bootrom_0/s_axi/reg0}] SEG_bootrom_$tag
    # SiFive test finisher (QEMU virt VIRT_TEST)
    create_bd_addr_seg -range 4K   -offset 0x00100000 \
        [get_bd_addr_spaces $master] \
        [get_bd_addr_segs {/finisher_0/s_axi/reg0}] SEG_finisher_$tag
    # 16550 UART (QEMU virt UART0). 128 KB covers the guest regs (low) and the
    # host TX-drain window at offset 0x10000.
    create_bd_addr_seg -range 128K -offset 0x10000000 \
        [get_bd_addr_spaces $master] \
        [get_bd_addr_segs {/uart_0/s_axi/reg0}] SEG_uart_$tag
    create_bd_addr_seg -range 4K   -offset 0x60000000 \
        [get_bd_addr_spaces $master] \
        [get_bd_addr_segs {/ctrl_0/s_axi/reg0}] SEG_ctrl_$tag
    create_bd_addr_seg -range 4K   -offset 0x60010000 \
        [get_bd_addr_spaces $master] \
        [get_bd_addr_segs {/axi_iic_0/S_AXI/Reg}] SEG_iic_$tag
    # HBM: 4 × 256 MB segments at 0x80000000..0xBFFFFFFF
    create_bd_addr_seg -range 256M -offset 0x80000000 \
        [get_bd_addr_spaces $master] \
        [get_bd_addr_segs {/hbm_0/SAXI_00/HBM_MEM00}] SEG_hbm0_$tag
    create_bd_addr_seg -range 256M -offset 0x90000000 \
        [get_bd_addr_spaces $master] \
        [get_bd_addr_segs {/hbm_0/SAXI_00/HBM_MEM01}] SEG_hbm1_$tag
    create_bd_addr_seg -range 256M -offset 0xA0000000 \
        [get_bd_addr_spaces $master] \
        [get_bd_addr_segs {/hbm_0/SAXI_00/HBM_MEM02}] SEG_hbm2_$tag
    create_bd_addr_seg -range 256M -offset 0xB0000000 \
        [get_bd_addr_spaces $master] \
        [get_bd_addr_segs {/hbm_0/SAXI_00/HBM_MEM03}] SEG_hbm3_$tag
    # Exclude unused HBM channels so SmartConnect doesn't route to them.
    foreach mem [list HBM_MEM04 HBM_MEM05 HBM_MEM06 HBM_MEM07 HBM_MEM08 \
                      HBM_MEM09 HBM_MEM10 HBM_MEM11 HBM_MEM12 HBM_MEM13 \
                      HBM_MEM14 HBM_MEM15 HBM_MEM16 HBM_MEM17 HBM_MEM18 \
                      HBM_MEM19 HBM_MEM20 HBM_MEM21 HBM_MEM22 HBM_MEM23 \
                      HBM_MEM24 HBM_MEM25 HBM_MEM26 HBM_MEM27 HBM_MEM28 \
                      HBM_MEM29 HBM_MEM30 HBM_MEM31] {
        catch {exclude_bd_addr_seg \
            [get_bd_addr_segs /hbm_0/SAXI_00/$mem] \
            -target_address_space [get_bd_addr_spaces $master]}
    }
}

assign_bd_address
validate_bd_design
