
# Block design: XDMA + HBM + CVA6 + bootrom + console + ctrl regs + I2C/PMIC
#
# Forest Kitten 33 (xcvu33p) variant of the cva6_xdma design.
# Modeled on SQRL_FK33/projects/fk33_example.tcl for HBM/clocking/PCIe topology,
# with the CVA6 master, bootrom, console buffer, and ctrl regs from the Acorn BD.
#
# Fabric clock: 250 MHz (xdma_0/axi_aclk). At Gen3 x4 the XDMA's axi-stream
# clock is fixed at 250 MHz. The SmartConnect, HBM AXI, and all peripherals
# run at 250 MHz. HBM ref clocks are 200 MHz and the HBM controller APB runs
# at 100 MHz — both generated by clk_wiz_0.
#
# Address map (unified — both XDMA host master and CVA6 see the same map):
#   0x0001_0000 .. 0x0001_0FFF   bootrom        (4 KB BRAM, CVA6 reset vector)
#   0x4000_0000 .. 0x4000_FFFF   console buffer
#   0x6000_0000 .. 0x6000_000F   ctrl regs      (reset, doorbell, status)
#   0x6001_0000 .. 0x6001_0FFF   axi_iic        (PMIC / on-board LEDs)
#   0x8000_0000 .. 0xBFFF_FFFF   HBM            (first 1 GiB of stack 0)
#
# HBM SAXI_00 native MEM00..MEM03 (each 256 MB) are remapped to 0x80000000..
# 0xBFFFFFFF on the master side via the SmartConnect. The remaining 28 HBM
# segments stay unmapped (and inaccessible) for this 1 GiB window.

##############
# PCIe / XDMA  — Gen3 x4 on PCIE4C_X1Y0
##############

create_bd_cell -type ip -vlnv xilinx.com:ip:xdma:4.1 xdma_0
# Stage 1: lock down PCIe block + link width/speed. axisten_freq's valid set
# depends on these — at Gen3 x4 the AXI-stream clock must be 250 MHz.
set_property -dict [list \
    CONFIG.pcie_blk_locn                {PCIE4C_X1Y0} \
    CONFIG.pl_link_cap_max_link_width   {X4} \
    CONFIG.pl_link_cap_max_link_speed   {8.0_GT/s} \
    CONFIG.ref_clk_freq                 {100_MHz} \
] [get_bd_cells xdma_0]
# Stage 2: fabric clock + interface mode.
set_property -dict [list \
    CONFIG.axisten_freq                 {250} \
    CONFIG.xdma_axi_intf_mm             {AXI_Memory_Mapped} \
    CONFIG.xdma_pcie_64bit_en           {true} \
] [get_bd_cells xdma_0]

# PCIe MGT lanes (top-level interface named "pcie")
make_bd_intf_pins_external [get_bd_intf_pins xdma_0/pcie_mgt]
set_property name pcie [get_bd_intf_ports pcie_mgt_0]

# PCIe 100 MHz refclk (diff pair via util_ds_buf in IBUFDSGTE mode)
create_bd_cell -type ip -vlnv xilinx.com:ip:util_ds_buf:2.2 util_ds_buf_pcie
set_property CONFIG.C_BUF_TYPE {IBUFDSGTE} [get_bd_cells util_ds_buf_pcie]
make_bd_intf_pins_external [get_bd_intf_pins util_ds_buf_pcie/CLK_IN_D]
set_property name pcie_refclk [get_bd_intf_ports CLK_IN_D_0]
connect_bd_net [get_bd_pins util_ds_buf_pcie/IBUF_DS_ODIV2] [get_bd_pins xdma_0/sys_clk]
connect_bd_net [get_bd_pins util_ds_buf_pcie/IBUF_OUT]      [get_bd_pins xdma_0/sys_clk_gt]

# PERST_N from the slot
make_bd_pins_external [get_bd_pins xdma_0/sys_rst_n]
set_property CONFIG.POLARITY ACTIVE_LOW [get_bd_ports sys_rst_n_0]
set_property name pcie_perstn [get_bd_ports sys_rst_n_0]

# CLKREQ# — tied constant high (some slots require it driven)
create_bd_cell -type ip -vlnv xilinx.com:ip:xlconstant:1.1 clkreq_const
set_property CONFIG.CONST_VAL {1} [get_bd_cells clkreq_const]
make_bd_pins_external [get_bd_pins clkreq_const/dout]
set_property name pcie_clkreq [get_bd_ports dout_0]

##############
# HBM (8 GiB total, global switch on — SAXI_00 reaches all channels)
##############

create_bd_cell -type ip -vlnv xilinx.com:ip:hbm:1.0 hbm_0
set_property -dict [list \
    CONFIG.USER_HBM_DENSITY              {8GB} \
    CONFIG.USER_HBM_STACK                {2} \
    CONFIG.USER_MEMORY_DISPLAY           {8192} \
    CONFIG.USER_HBM_REF_CLK_0            {200} \
    CONFIG.USER_HBM_REF_CLK_1            {200} \
    CONFIG.USER_AXI_INPUT_CLK_FREQ       {250} \
    CONFIG.USER_AXI_INPUT_CLK1_FREQ      {250} \
    CONFIG.USER_APB_EN                   {false} \
    CONFIG.USER_CLK_SEL_LIST0            {AXI_00_ACLK} \
    CONFIG.USER_CLK_SEL_LIST1            {AXI_16_ACLK} \
] [get_bd_cells hbm_0]

# Disable all SAXI ports except SAXI_00 (only master we use; global switch
# lets SAXI_00 reach all 32 channels across both stacks).
foreach i {01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31} {
    set_property CONFIG.USER_SAXI_$i {false} [get_bd_cells hbm_0]
}

##############
# Clock generation
#   clk_in1  = 250 MHz from xdma/axi_aclk
#   clk_out1 = 100 MHz APB clock for HBM controller APB
#   clk_out2 = 200 MHz HBM_REF_CLK_0/1
#   clk_out3 = cpu_freq_mhz CVA6 clock
##############

create_bd_cell -type ip -vlnv xilinx.com:ip:clk_wiz:6.0 clk_wiz_0
set_property -dict [list \
    CONFIG.PRIM_IN_FREQ                 {250.000} \
    CONFIG.RESET_TYPE                   {ACTIVE_LOW} \
    CONFIG.RESET_PORT                   {resetn} \
    CONFIG.USE_LOCKED                   {true} \
    CONFIG.CLKOUT1_USED                 {true} \
    CONFIG.CLKOUT1_REQUESTED_OUT_FREQ   {100.000} \
    CONFIG.CLKOUT2_USED                 {true} \
    CONFIG.CLKOUT2_REQUESTED_OUT_FREQ   {200.000} \
    CONFIG.CLKOUT3_USED                 {true} \
    CONFIG.CLKOUT3_REQUESTED_OUT_FREQ   $cpu_freq_mhz \
] [get_bd_cells clk_wiz_0]
connect_bd_net [get_bd_pins xdma_0/axi_aclk]     [get_bd_pins clk_wiz_0/clk_in1]
connect_bd_net [get_bd_pins xdma_0/axi_aresetn]  [get_bd_pins clk_wiz_0/resetn]

# Reset for HBM domain (100 MHz APB clock)
create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 hbm_reset
connect_bd_net [get_bd_pins clk_wiz_0/clk_out1]  [get_bd_pins hbm_reset/slowest_sync_clk]
connect_bd_net [get_bd_pins clk_wiz_0/locked]    [get_bd_pins hbm_reset/dcm_locked]
connect_bd_net [get_bd_pins xdma_0/axi_aresetn]  [get_bd_pins hbm_reset/ext_reset_in]

# HBM clock/reset wiring
connect_bd_net [get_bd_pins clk_wiz_0/clk_out2]      [get_bd_pins hbm_0/HBM_REF_CLK_0]
connect_bd_net [get_bd_pins clk_wiz_0/clk_out2]      [get_bd_pins hbm_0/HBM_REF_CLK_1]
connect_bd_net [get_bd_pins clk_wiz_0/clk_out1]      [get_bd_pins hbm_0/APB_0_PCLK]
connect_bd_net [get_bd_pins clk_wiz_0/clk_out1]      [get_bd_pins hbm_0/APB_1_PCLK]
connect_bd_net [get_bd_pins hbm_reset/peripheral_aresetn] [get_bd_pins hbm_0/APB_0_PRESET_N]
connect_bd_net [get_bd_pins hbm_reset/peripheral_aresetn] [get_bd_pins hbm_0/APB_1_PRESET_N]
connect_bd_net [get_bd_pins xdma_0/axi_aclk]         [get_bd_pins hbm_0/AXI_00_ACLK]
connect_bd_net [get_bd_pins xdma_0/axi_aresetn]      [get_bd_pins hbm_0/AXI_00_ARESET_N]

##############
# CPU clock domain reset
##############

create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 cpu_rstgen
connect_bd_net [get_bd_pins clk_wiz_0/clk_out3]  [get_bd_pins cpu_rstgen/slowest_sync_clk]
connect_bd_net [get_bd_pins clk_wiz_0/locked]    [get_bd_pins cpu_rstgen/dcm_locked]
connect_bd_net [get_bd_pins xdma_0/axi_aresetn]  [get_bd_pins cpu_rstgen/ext_reset_in]

##############
# CVA6 wrapper
##############

create_bd_cell -type module -reference cva6_acorn_wrapper cva6_0
connect_bd_net [get_bd_pins clk_wiz_0/clk_out3] [get_bd_pins cva6_0/clk]

# CVA6 master → axi_aclk SmartConnect
create_bd_cell -type ip -vlnv xilinx.com:ip:axi_clock_converter:2.1 cva6_axi_cc
connect_bd_intf_net [get_bd_intf_pins cva6_0/m_axi] [get_bd_intf_pins cva6_axi_cc/S_AXI]
connect_bd_net [get_bd_pins clk_wiz_0/clk_out3]            [get_bd_pins cva6_axi_cc/s_axi_aclk]
connect_bd_net [get_bd_pins cpu_rstgen/peripheral_aresetn] [get_bd_pins cva6_axi_cc/s_axi_aresetn]
connect_bd_net [get_bd_pins xdma_0/axi_aclk]               [get_bd_pins cva6_axi_cc/m_axi_aclk]
connect_bd_net [get_bd_pins xdma_0/axi_aresetn]            [get_bd_pins cva6_axi_cc/m_axi_aresetn]

##############
# AXI SmartConnect — 2 masters (XDMA, CVA6), 5 slaves
#   M00: HBM SAXI_00
#   M01: bootrom
#   M02: console
#   M03: ctrl_regs
#   M04: axi_iic (PMIC + LEDs)
##############

create_bd_cell -type ip -vlnv xilinx.com:ip:smartconnect:1.0 axi_smc
set_property -dict [list \
    CONFIG.NUM_SI {2} \
    CONFIG.NUM_MI {5} \
    CONFIG.NUM_CLKS {1} \
] [get_bd_cells axi_smc]
connect_bd_net [get_bd_pins xdma_0/axi_aclk]    [get_bd_pins axi_smc/aclk]
connect_bd_net [get_bd_pins xdma_0/axi_aresetn] [get_bd_pins axi_smc/aresetn]

connect_bd_intf_net [get_bd_intf_pins xdma_0/M_AXI]      [get_bd_intf_pins axi_smc/S00_AXI]
connect_bd_intf_net [get_bd_intf_pins cva6_axi_cc/M_AXI] [get_bd_intf_pins axi_smc/S01_AXI]
connect_bd_intf_net [get_bd_intf_pins axi_smc/M00_AXI]   [get_bd_intf_pins hbm_0/SAXI_00]

##############
# Bootrom (4 KB at 0x10000)
##############

create_bd_cell -type module -reference axi_bram_init bootrom_0
set_property -dict [list \
    CONFIG.MEM_INIT_FILE {bootrom.memh} \
    CONFIG.DEPTH_WORDS   {1024} \
] [get_bd_cells bootrom_0]
connect_bd_net [get_bd_pins xdma_0/axi_aclk]    [get_bd_pins bootrom_0/axi_clk]
connect_bd_net [get_bd_pins xdma_0/axi_aresetn] [get_bd_pins bootrom_0/axi_resetn]
connect_bd_intf_net [get_bd_intf_pins axi_smc/M01_AXI] [get_bd_intf_pins bootrom_0/s_axi]

##############
# Console buffer (64 KB at 0x40000000)
##############

create_bd_cell -type module -reference axi_console_buffer console_0
connect_bd_net [get_bd_pins xdma_0/axi_aclk]    [get_bd_pins console_0/axi_clk]
connect_bd_net [get_bd_pins xdma_0/axi_aresetn] [get_bd_pins console_0/axi_resetn]
connect_bd_intf_net [get_bd_intf_pins axi_smc/M02_AXI] [get_bd_intf_pins console_0/s_axi]

##############
# Control registers (16 B at 0x60000000)
##############

create_bd_cell -type module -reference axi_ctrl_regs ctrl_0
connect_bd_net [get_bd_pins xdma_0/axi_aclk]    [get_bd_pins ctrl_0/axi_clk]
connect_bd_net [get_bd_pins xdma_0/axi_aresetn] [get_bd_pins ctrl_0/axi_resetn]
connect_bd_intf_net [get_bd_intf_pins axi_smc/M03_AXI] [get_bd_intf_pins ctrl_0/s_axi]

# CVA6 reset: feed the host-controlled reset (ctrl_regs/cva6_rst_n, launched in
# the ui_clk/axi domain) through cpu_rstgen's aux_reset_in so proc_sys_reset
# synchronises its release to cpu_clk. This replaces the old combinational AND,
# which crossed ui_clk->cpu_clk (related clocks via the MMCM) unsynchronised and
# produced a ~23k-fanout reset with negative hold slack. aux_reset_in is
# active-low by default, matching cva6_rst_n.
connect_bd_net [get_bd_pins ctrl_0/cva6_rst_n]             [get_bd_pins cpu_rstgen/aux_reset_in]
connect_bd_net [get_bd_pins cpu_rstgen/peripheral_aresetn] [get_bd_pins cva6_0/rst_n]

# Host→CVA6 IRQ (PLIC src 1), CVA6→host IRQ (XDMA usr_irq)
connect_bd_net [get_bd_pins ctrl_0/host_irq]     [get_bd_pins cva6_0/host_irq]
connect_bd_net [get_bd_pins ctrl_0/host_irq_out] [get_bd_pins xdma_0/usr_irq_req]

##############
# AXI I2C (PMIC + 7 LEDs)
##############

create_bd_cell -type ip -vlnv xilinx.com:ip:axi_iic:2.1 axi_iic_0
set_property -dict [list \
    CONFIG.C_GPO_WIDTH    {7} \
    CONFIG.C_DEFAULT_VALUE {0x40} \
] [get_bd_cells axi_iic_0]
connect_bd_net [get_bd_pins xdma_0/axi_aclk]    [get_bd_pins axi_iic_0/s_axi_aclk]
connect_bd_net [get_bd_pins xdma_0/axi_aresetn] [get_bd_pins axi_iic_0/s_axi_aresetn]
connect_bd_intf_net [get_bd_intf_pins axi_smc/M04_AXI] [get_bd_intf_pins axi_iic_0/S_AXI]
make_bd_intf_pins_external [get_bd_intf_pins axi_iic_0/IIC]
set_property name iic [get_bd_intf_ports IIC_0]

# LEDs: GPO inverted (LEDs are active-low on FK33)
create_bd_cell -type ip -vlnv xilinx.com:ip:util_vector_logic:2.0 led_inv
set_property -dict [list CONFIG.C_OPERATION {not} CONFIG.C_SIZE {7}] [get_bd_cells led_inv]
connect_bd_net [get_bd_pins axi_iic_0/gpo] [get_bd_pins led_inv/Op1]
make_bd_pins_external [get_bd_pins led_inv/Res]
set_property name led [get_bd_ports Res_0]

##############
# Address map — both XDMA and CVA6 see the unified map.
# HBM SAXI_00/HBM_MEM00..03 are placed at 0x80000000 (1 GiB window).
##############

set masters {/xdma_0/M_AXI /cva6_0/m_axi}

foreach master $masters {
    set tag [expr {$master eq "/xdma_0/M_AXI" ? "xdma" : "cva6"}]
    create_bd_addr_seg -range 4K  -offset 0x00010000 \
        [get_bd_addr_spaces $master] \
        [get_bd_addr_segs {/bootrom_0/s_axi/reg0}] SEG_bootrom_$tag
    create_bd_addr_seg -range 64K -offset 0x40000000 \
        [get_bd_addr_spaces $master] \
        [get_bd_addr_segs {/console_0/s_axi/reg0}] SEG_console_$tag
    create_bd_addr_seg -range 4K  -offset 0x60000000 \
        [get_bd_addr_spaces $master] \
        [get_bd_addr_segs {/ctrl_0/s_axi/reg0}] SEG_ctrl_$tag
    create_bd_addr_seg -range 4K  -offset 0x60010000 \
        [get_bd_addr_spaces $master] \
        [get_bd_addr_segs {/axi_iic_0/S_AXI/Reg}] SEG_iic_$tag
    # HBM: 4 × 256 MB segments at 0x80000000..0xBFFFFFFF
    create_bd_addr_seg -range 256M -offset 0x80000000 \
        [get_bd_addr_spaces $master] \
        [get_bd_addr_segs {/hbm_0/SAXI_00/HBM_MEM00}] SEG_hbm0_$tag
    create_bd_addr_seg -range 256M -offset 0x90000000 \
        [get_bd_addr_spaces $master] \
        [get_bd_addr_segs {/hbm_0/SAXI_00/HBM_MEM01}] SEG_hbm1_$tag
    create_bd_addr_seg -range 256M -offset 0xA0000000 \
        [get_bd_addr_spaces $master] \
        [get_bd_addr_segs {/hbm_0/SAXI_00/HBM_MEM02}] SEG_hbm2_$tag
    create_bd_addr_seg -range 256M -offset 0xB0000000 \
        [get_bd_addr_spaces $master] \
        [get_bd_addr_segs {/hbm_0/SAXI_00/HBM_MEM03}] SEG_hbm3_$tag
    # Exclude unused HBM channels so SmartConnect doesn't route to them.
    foreach mem [list HBM_MEM04 HBM_MEM05 HBM_MEM06 HBM_MEM07 HBM_MEM08 \
                      HBM_MEM09 HBM_MEM10 HBM_MEM11 HBM_MEM12 HBM_MEM13 \
                      HBM_MEM14 HBM_MEM15 HBM_MEM16 HBM_MEM17 HBM_MEM18 \
                      HBM_MEM19 HBM_MEM20 HBM_MEM21 HBM_MEM22 HBM_MEM23 \
                      HBM_MEM24 HBM_MEM25 HBM_MEM26 HBM_MEM27 HBM_MEM28 \
                      HBM_MEM29 HBM_MEM30 HBM_MEM31] {
        catch {exclude_bd_addr_seg \
            [get_bd_addr_segs /hbm_0/SAXI_00/$mem] \
            -target_address_space [get_bd_addr_spaces $master]}
    }
}

assign_bd_address
validate_bd_design
